apiVersion: v1
kind: Secret
metadata:
  name: xnat-secrets
  namespace: xnat
  labels:
    app.kubernetes.io/name: xnat
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials
  datasource-password: "xnat"
  postgres-admin-password: "postgres"

  # ActiveMQ credentials
  activemq-username: "admin"
  activemq-password: "admin"
