apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: xnat-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  bootstrap:
    initdb:
      database: xnat
      owner: xnat
      secret:
        name: xnat-db-credentials
  monitoring:
    enablePodMonitor: false
